version: 2

jobs:
  build:
    docker:
      - image: rust:1.31
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo build
      - run: cargo test
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
