version: 2

jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: rustup component add rustfmt-preview
      - run: cargo build
      - run: cargo test
      - run: cargo fmt -- --write-mode=diff
